version: "3.8"

services:
  # Frontend service
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: client
    volumes:
      - client_build:/client/build

  # Nginx service
  nginx:
    # build:
    # context: ./nginx
    # dockerfile: Dockerfile
    container_name: nginx
    image: nginx:1.21-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      # - ./data/certbot/conf:/etc/letsencrypt
      # - ./data/certbot/www:/var/www/certbot

      # - ./nginx/prod:/etc/nginx/conf.d
      - ./nginx/dev:/etc/nginx/conf.d

      - client_build:/etc/nginx/html/
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''
    depends_on:
      - client
    restart: always

  # CertBot service *in production mode
  # certbot:
  #   image: certbot/certbot
  #   volumes:
  #     - ./data/certbot/conf:/etc/letsencrypt
  #     - ./data/certbot/www:/var/www/certbot
  #   entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
  #   depends_on:
  #     - nginx

# Volumes
volumes:
  client_build:
